Add initial r5q support
edk2-porting/edk2-msm pull request #232
Opened 2023-01-18 15:51 UTC by Icesito68

### Description

The buttons work partially, only the top one is missing, and the ufs is read perfectly, also the uefi interface is perfect

### Checklist

* [y] Have you tested the change you are submitting?
* [y] Is the commits history nice and clean?

2023-01-18 17:51 UTC, ungeskriptet commented
You can use your ButtonsDxe from extracted xbl just fine. SimpleInit is made to work with unpatched ButtonsDxe, the only usecase for patched ButtonsDxe is to have enter working in GRUB. Using drivers from other devices could potentially be dangerous.

2023-01-18 17:54 UTC, Icesito68 commented
but if I'm not mistaken I have not used drivers from another device for the buttons, unless I was wrong

2023-01-19 09:52 UTC, ungeskriptet commented
> but if I'm not mistaken I have not used drivers from another device for the buttons, unless I was wrong

You are, look in file Platform/Samsung/sm8150/r5q.fdf.inc line 11.

2023-01-19 11:41 UTC, qaz6750 requested changes

2023-01-19 11:41 UTC, qaz6750 commented on Platform/Samsung/sm8150/r5q.fdf.inc
> +   SECTION PE32 = Platform/EFI_Binaries/Drivers/Devices/vayu/ButtonsDxe/ButtonsDxe.efi
I don't understand why we should use ButtonsDxe and DALSys of other devices. Even though they can work, I don't think they should be used in this way

2023-01-19 12:18 UTC, closed without merging