Main
edk2-porting/edk2-msm pull request #350
Opened 2023-10-01 13:38 UTC by msumro

### Description

[Description of the changes you are submitting]

### Checklist

* [ ] Have you tested the change you are submitting?
* [ ] Is the commits history nice and clean?

2023-10-01 13:39 UTC, halal-beef commented
.... what is this

2023-10-01 13:43 UTC, J0SH1X requested changes
Please merge this in properly without removing support for other devices.

2023-10-01 14:13 UTC, NetuserPRO commented
@msumro fix it

2023-10-01 14:13 UTC, msumro commented
@NetuserPRO Edited it

2023-10-01 15:16 UTC, qaz6750 commented on Platform/Xiaomi/sm8250/munch.dsc
May I ask why the support for alioth devices has been removed?

2023-10-01 15:17 UTC, qaz6750 commented on =
May I ask why there are these junk files ？

2023-10-01 15:18 UTC, qaz6750 commented on Platform/Xiaomi/sm8250/Library/munch/PlatformMemoryMapLib/PlatformMemoryMapLib.c
This has nothing to do with adding new device support for you

2023-10-01 15:18 UTC, qaz6750 commented on Silicon/Qualcomm/QcomPkg/Include/Library/FrameBufferSerialPortLib.h
This has nothing to do with adding new device support for you

2023-10-01 15:28 UTC, qaz6750 requested changes
Please note:
* Your submission contains some junk files
*  Secondly, I don't know why you deleted alioth to support your munch device, which is incorrect
* In addition, this submission contains many changes for other purposes, and you should not include them in this submission, which is very confusing

2023-10-03 05:59 UTC, msumro commented
Good, i also deleted that

2023-10-03 06:02 UTC, halal-beef commented
@msumro ??

2023-10-04 07:08 UTC, closed without merging